### ISSUE TITLE
更新你的代码报错了，之前正常

### ISSUE THREAD

**Issue by hjldev** [linlianmin/laravel-vue#12]
User类的6个抽象方法没有重写，在填充数据库的时候报错
<img width="798" alt="7bd31c4b-11de-4a9f-bfa4-01dee6c4faae" src="https://user-images.githubusercontent.com/17423465/33057332-4a3aaf8a-cec5-11e7-8e3b-bcafd230f314.png">

**Comment by linlianmin** [comment]
谢谢，已修复
